### ISSUE TITLE
初始化后滑块在左侧，点击两次后才会在右侧

### ISSUE THREAD

**Issue by zjy7** [zhiyul/switch#11]
```
var options={
    checked:true,
    size: 'small'
}
var mySwitch = new Switch(el,options);
```
![image](https://user-images.githubusercontent.com/14885404/29738607-6619386c-8a59-11e7-9777-a419e1878b85.png)

**Comment by slince** [comment]
+1

**Comment by slince** [comment]
当switch所在区域初始化是 `display:none` 时, `jack` 的 `left` 值计算会有问题

[https://github.com/zhiyul/switch/blob/a4eeef829ba282e662ed6f53baebc3a564c672a2/src/switch.js#L267](https://github.com/zhiyul/switch/blob/a4eeef829ba282e662ed6f53baebc3a564c672a2/src/switch.js#L267)

`clientWidth`的值在元素不可见时是0，所以left计算出来还是0；所以换成

```js
parseInt(window.getComputedStyle(this._switch).width) - parseInt(window.getComputedStyle(this._jack).width);
```
来计算比较好一点

**Comment by slince** [comment]
#13   麻烦合并下，这个bug卡着太难受了

**Comment by slince** [comment]
@zhiyul
