### ISSUE TITLE
display bug when checked ?

### ISSUE THREAD

**Issue by simogeo** [zhiyul/Switch#6]
Working with default `checked  : undefined` value and applying Switch to the following html

``` html
<input type="checkbox" checked="checked" value="1" id="notify-user" name="notify-user" class="checkbox-switch">
```

I get this result and this is what I am expected :  
![b](https://cloud.githubusercontent.com/assets/154323/17137923/10c4166e-533e-11e6-9465-71f729d62527.png)

THe color is ok but the position is incorrect. Any idea on how to fix this ?

@zhiyul : BTW, nice library ! thanks

**Comment by simogeo** [comment]
Any news regarding this ?

**Comment by zhiyul** [comment]
The code is updated, you can try it. But if the error shows again, please provide an online demo, I didn't get the error according to your description : )

**Comment by zhiyul** [comment]
@simogeo online urls are https://unpkg.com/weatherstar-switch@1.0.7/dist/switch.js and https://unpkg.com/weatherstar-switch@1.0.7/dist/switch.css . Try https://jsfiddle.net/

**Comment by simogeo** [comment]
Thanks. Actually, I switch to full css option .... but I wanted to let you know about that. Not sure to have time to try this.

Thanks again

**Comment by zhiyul** [comment]
@simogeo Thanks for your support 😄
